name: my_repository
description: Description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dart_code_metrics: ^4.17.1
  dio: ^4.0.6
  dio_service:
    path: ../dio_service
  equatable: ^2.0.3
  fast_immutable_collections: ^7.4.1
  fpdart: ^0.3.0
  freezed_annotation: ^2.0.3
  freezer: ^0.6.1
  hive: ^2.2.3
  hive_repository:
    path: ../hive_repository
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.5.0
  freezed: ^2.0.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1
  test: ^1.21.4
  very_good_analysis: ^3.1.0
