name: my_repository
description: Description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.16.0
  dio: ^4.0.6
  fpdart: ^0.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4
  stash: ^4.3.0

dependency_overrides: 
  # fix for https://github.com/rrousselGit/freezed/issues/700
  analyzer: ">=4.2.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.5.0
  freezed: ^2.0.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1
  test: ^1.21.4
  very_good_analysis: ^3.0.1
