name: flitaa_extensions
description: A Very Good Project created by Very Good CLI.
version: 1.1.0-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: { intl: any, rxdart: ^0.27.7, stash: ^4.5.3 }

dev_dependencies:
  mocktail: ^0.3.0
  test: any
  very_good_analysis: ^4.0.0+1
