name: flitaa_extensions
description: A Very Good Project created by Very Good CLI.
version: 1.1.0-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: { intl: ^0.17.0, rxdart: ^0.27.4, stash: ^4.3.4 }

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
