name: hive_repository
description: A dart package that simplifies creating Local Data Sources using Hive.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # analyzer
  dart_code_metrics: ^5.7.2

  hive: ^2.2.3
  synchronized: ^3.1.0

dev_dependencies:
  build_runner: any
  freezed: ^2.3.3
  hive_generator: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: any
  very_good_analysis: "^4.0.0+1"
