name: crashlytics_service
description: Flutter package with useful functions from firebase crashlytics.
version: 1.1.0-dev.3
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dart_code_metrics: ^4.17.1
  firebase_crashlytics: ^3.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
