name: {{package_name.snakeCase()}}
description: {{package_description}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:{{#analysis}}
  dart_code_metrics: ^4.17.1{{/analysis}}
  dio: ^4.0.6
  dio_service:
    git: https://github.com/Prn-Ice/dio_service.git
  equatable: ^2.0.3
  fast_immutable_collections: ^7.4.1
  fpdart: ^0.3.0{{#flutter}}
  flutter:
    sdk: flutter{{/flutter}}
  freezed_annotation: ^2.0.3
  freezer: ^0.6.1
  hive: ^2.2.3
  hive_repository:
    git: https://github.com/Prn-Ice/hive_repository.git
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4

dev_dependencies:{{#notFlutter}}
  build_runner: ^2.1.11
  coverage: ^1.5.0{{/notFlutter}}{{#flutter}}
  flutter_test:
    sdk: flutter{{/flutter}}
  freezed: ^2.0.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1{{#notFlutter}}
  test: ^1.21.4{{/notFlutter}}
  very_good_analysis: ^3.1.0
