repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          # -   id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.32.2
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/fluttercommunity/import_sorter
      rev: "f350497a11b1285c695595049e95a420068e7a9f"
      hooks:
          - id: dart-import-sorter
