name: my_app
sdkPath: .fvm/flutter_sdk
packages:
  - packages/*
  - "."

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze: melos exec -- "dart analyze ."

  metrics:
    run: |
      melos exec -c 1 --ignore="*example*" -- \
        flutter pub run dart_code_metrics:metrics analyze lib
    description: |
      Run `dart_code_metrics` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --coverage --test-randomize-ordering-seed random --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - "*web*"
        - "*odm*"
        - "*example*"
