name: service_class
description: decription
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

dev_dependencies:
  coverage: ^1.4.0
  mocktail: ^0.3.0
  test: ^1.21.2
  very_good_analysis: ^3.0.1
