name: example
description: A simple command-line application.
version: 1.1.0-dev.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  hive: ^2.2.2
  hive_repository:
    path: ../
  rxdart: ^0.27.4

dev_dependencies:
  very_good_analysis: "^3.0.1"
