name: {{#snakeCase}}{{project_name}}{{/snakeCase}}
sdkPath: .fvm/flutter_sdk
packages:
  - packages/*
  - "."

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze: melos exec -- "dart analyze ."

  metrics:
    run: |
      melos exec -c 1 --ignore="*example*" -- \
        flutter pub run dart_code_metrics:metrics analyze lib
    description: |
      Run `dart_code_metrics` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  generate_localization:
    run: |
      melos exec -- \
        flutter pub run easy_localization:generate -S assets/translations/ -O lib/gen/ && flutter pub run easy_localization:generate -S assets/translations/ -O lib/gen/ -f keys -o locale_keys.g.dart
    description: Generate localization files for easy_localization.
    select-package:
      flutter: true
      scope: "{{#snakeCase}}{{project_name}}{{/snakeCase}}"

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --coverage --test-randomize-ordering-seed random --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - "*web*"
        - "*odm*"
        - "*example*"
