name: {{#snakeCase}}{{project_name}}{{/snakeCase}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  app_ui:
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  dots_indicator: ^2.1.0
  dropdown_button2: ^1.6.3
  equatable: ^2.0.3
  expandable_page_view: ^1.0.17
  fast_immutable_collections: ^7.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: "^5.5.3+2"
  flutter_svg: ^1.1.1+1
  fpdart: ^0.1.0
  humanizer: ^2.0.0
  intl: ^0.17.0
  nil: ^1.1.1
  objectbox_flutter_libs: ^1.6.0
  skeleton_animation: ^0.1.4

  # analytics
  dart_code_metrics: ^4.16.0

  # db
  stash: ^4.3.0
  stash_objectbox: ^4.3.0

  # form utils
  formz: ^0.4.1

  # logger
  auto_route_observer:
  bloc_logger:

  # repository

  # routing
  auto_route: "^4.2.1"

  # state management
  flutter_bloc: "^8.0.1"
  flutter_hooks: ^0.18.5+1
  get_it: "^7.2.0"
  platform_info: ^3.2.0
  auto_size_text: ^3.0.0

dependency_overrides:
  async: 2.8.2
  clock: 1.1.0
  meta: 1.7.0
  path: 1.8.1

dev_dependencies:
  auto_route_generator: "^4.0.0"
  bloc_test: ^9.0.3
  build_runner: "^2.1.11"
  flutter_gen_runner: ^4.3.0
  flutter_native_splash: "^2.2.3+1"
  flutter_test:
    sdk: flutter
  injectable_generator: "^1.5.3"
  mocktail: ^0.3.0
  rename:
    git:
      url: https://github.com/Prn-Ice/rename.git
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
