name: hive_service
description: Dart project with useful functions to use with the Hive package.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dart_code_metrics: ^5.7.2
  flutter:
    sdk: flutter
  fpdart: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: "^0.3.0"
  very_good_analysis: "^4.0.0+1"
