name: riverpod_logger
description: Dart package for a riverpod observer that prints output using logger.
version: 1.1.0-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: {crashlytics_service, dart_code_metrics: ^4.17.1, logger: ^1.1.0, riverpod: ^2.1.1}

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
