name: riverpod_logger
description: Dart package for a riverpod observer that prints output using logger.
version: 1.1.0-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crashlytics_service:
    path: "../crashlytics_service"
  dart_code_metrics: ^5.7.2
  riverpod: ^2.3.6
  talker: ^2.4.0

dev_dependencies:
  mocktail: ^0.3.0
  test: any
  very_good_analysis: ^4.0.0+1
