name: crashlytics_service
description: Flutter package with useful functions from firebase crashlytics.
version: 1.1.0-dev.3
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dart_code_metrics: ^5.7.2
  firebase_crashlytics: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
